[package]
name = "cobalt-ui"
version = "0.0.1"
authors = ["Drew Powers <drew@pow.rs>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0", optional = true }
json = "*"
lazy_static = "*"
regex = "*"
wasm-bindgen = "0"
wee_alloc = { version = "0", optional = true }
yaml-rust = "*"

[dev-dependencies]
wasm-bindgen-test = "0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
